"""


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

sumOfFibos = 0
n1 = 0
n2 = 1

while n2 < 4000001:
	if n2 % 2 == 0:
		sumOfFibos += n2
	n1, n2 = n2, n1 + n2
	
print sumOfFibos

# 4613732
